# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

terms = [1,2]
even_valued_terms = [2]
current_term = 2
sum = 0

loop do
  current_term = terms[-1] + terms[-2]
  
  break if current_term > 4000000
  
  terms.push(current_term)
  even_valued_terms.push(current_term) if current_term.even?
end

even_valued_terms.each do |n|
  sum += n
end

puts sum
